### PR TITLE
Improve client-side build process

### PR DESCRIPTION
**Pull request by afiore**
Improves client-side build process (paired with @davidrapson)

- **Moved assets from `app/assets` to `assets/`**
- Remove minified JS/CSS assets from version control
- Removed `jspm` for now as it was installed but not hooked up to anything so better to stick to working `requirejs` + `bower` combo for now. We can revisit this at a later date
- Cleans up `Gruntfile`, upgrades to newer `grunt-sass` which removes the `ruby` dependency.
- Setup grunt tasks for copying, cleaning and hashing assets
- Add `util.Asset` for reading `assets.map`
- Move Omniture JS into assets and copy it to dist
- Move images into assets
- Updated links to assets
- Adds `grunt-tc` script for TeamCity

### CODE REVIEW

**Comment by davidrapson** [comment]
Paired with @afiore to clean up client-side build process:

- Removed `jspm` for now as it was installed but not hooked up to anything so better to stick to working `requirejs` + `bower` combo for now. We can revisit this at a later date
- Cleans up `Gruntfile`, upgrades to newer `grunt-sass` which removes the `ruby` dependency.

**Comment by davidrapson** [comment]
TeamCity now configured to compile and hash assets as part of build process.

screen shot 2015-06-16 at 17 03 35

**Comment by davidrapson** [comment]
@rtyley @jennysivapalan

**Comment by rtyley** [comment]
LFGTM :+1:

**Comment by davidrapson** [comment]
I'm happy with where we got to with this too :+1: :+1: , @afiore we should walk through deploying this in the morning.

**Comment by jennysivapalan** [comment]
Great stuff - thanks botg :+1: :house:

**Comment by afiore** [comment]
Deployed manually and verified on a single ec2 instance. Merging it into master

**Comment by davidrapson** [comment]
:fireworks: :tada: :speedboat:

**Comment by afiore** [comment]
Verified on live site. Layout looks fine, however the generated jar does not seem to include the source-map file `min.css.map`. Adding a new PR to address this issue

**Pull request merged**
