### PR TITLE
Do not allow managing cancelled subs

### PR DESCRIPTION
**Pull request by pvighi**
Logging in to /manage with a cancelled home delivery sub causes a 500 error.  [trello card](https://trello.com/c/KFnLL0AM/50-improve-handling-of-cancelled-subs-who-try-to-access-manage)

@jacobwinch  mentioned that there are similar problems with other types of subs, for example attempting to renew a cancelled subscription.

This change filters out cancelled subs so the user would get an "Unable to verify your details" error when trying to log in.

@johnduffell @jacobwinch @paulbrown1982

### CODE REVIEW

**Comment by johnduffell** [comment]
If the details are correct and we actually know it's cancelled, we should be more helpful.. it's not like we need to be cagey about the reason if the details are accurate

**Comment by johnduffell** [comment]
however this is an improvement on a 500 error and a quick fix, so I'll leave it to future improvement or up to you for the message 👍

**Comment by paulbrown1982** [comment]
👍 too

**Comment by pvighi** [comment]
I added a custom error message for cancelled subs in /manage. I'm open to suggestions on the exact wording, date format or anything else
canc

**Comment by pvighi** [comment]
changed date format
canc

**Comment by johnduffell** [comment]
👍 :1st_place_medal:

**Pull request merged**
