### PR TITLE
Basic regression tests for Print, and Print + Digital subscriptions

### PR DESCRIPTION
**Pull request by afiore**
Implements a small regression test covering the Print-only and Print + Digital subscriptions workflow. This can be run locally (against `https://sub.thegulocal.com`), or against the production site. 

@TesterSpike @rtyley

### CODE REVIEW

**Comment by TesterSpike** [comment]
:+1:

**Comment by tudorraul** [comment]
is TC configured for this?

**Comment by afiore** [comment]
@tudorraul I tried the configuration yesterday and it works fine. Just need to change the sbt *test* task into *fast-test* and it will work fine.

**Comment by afiore** [comment]
Verified on [Teamcity](http://teamcity.guprod.gnm/viewLog.html?buildId=697632&tab=buildResultsDiv&buildTypeId=Subscriptions_ProdAcceptanceTest)

**Pull request merged**
