### PR TITLE
reveal Guardian Weekly Price Rise on /manage - only within 30days

### PR DESCRIPTION
**Pull request by twrichards**
To coordinate with the Guardian Weekly Price Rise letters, this PR ensures that the price rise is only visible online for 30 days in advance, and that the ugly internal name for the product rate plan is no longer exposed.

| Before | After |
| --- | --- |
| image | image | 

If a price rise is inferred (product rate plans don't match on future plans) and the price rise is due more than 30 days ahead, in addition to hiding the 'Upcoming Plan', the current plan is passed into the `billingSchedule` and is then compared with each bill amount, if the bill amount is larger than the currentPlan amount then the current plan amount is used instead, which should support the temporary discounts without revealing the price rise before the 30 days

### CODE REVIEW

**Comment by jacobwinch** [comment]
> the billing schedule uses the price of the first invoice for all the other invoices (this is messy but since it's limited to Guardian Weekly it should be fine)

I've been thinking about this a little more... I doubt there will be many real examples of this, but if there is a temporary discount on the subscription this display could be a little misleading. As an alternative, we could hide all scheduled payments that are >= price rise date?

**Comment by twrichards** [comment]
> > the billing schedule uses the price of the first invoice for all the other invoices (this is messy but since it's limited to Guardian Weekly it should be fine)
> 
> I've been thinking about this a little more... I doubt there will be many real examples of this, but if there is a temporary discount on the subscription this display could be a little misleading. As an alternative, we could hide all scheduled payments that are >= price rise date?

@jacobwinch my only fear with that is that, as the price rise approaches the billing schedule will have only one or two entries, implying that their subscription is coming to an end (imagine it on the screenshot above) this would be misleading for a lot of users rather than only a few in the case of temp. discounts.
I will see if I can do some sort of Hybrid...

**Comment by twrichards** [comment]
> > > the billing schedule uses the price of the first invoice for all the other invoices (this is messy but since it's limited to Guardian Weekly it should be fine)
> > 
> > 
> > I've been thinking about this a little more... I doubt there will be many real examples of this, but if there is a temporary discount on the subscription this display could be a little misleading. As an alternative, we could hide all scheduled payments that are >= price rise date?
> 
> @jacobwinch my only fear with that is that, as the price rise approaches the billing schedule will have only one or two entries, implying that their subscription is coming to an end (imagine it on the screenshot above) this would be misleading for a lot of users rather than only a few in the case of temp. discounts.
> I will see if I can do some sort of Hybrid...

@jacobwinch I've improved how this works... now the current plan is passed into the `billingSchedule` if an upcoming rate plan change is more than 30days away, and is then compared with each bill amount, if the bill amount is larger than the currentPlan amount then the current plan amount is used instead, which should support the temporary discounts without revealing the price rise before the 30 days

**Comment by jacobwinch** [comment]
New approach to handling the billing schedule sounds good 👍

**Pull request merged**
