### PR TITLE
Use membership commons code for Zuora interactions

### PR DESCRIPTION
**Pull request by afiore**
Removes zuora-related duplication and push `Subscription` action into membership commons. 

@rtyley @ostapneko

### CODE REVIEW

**Comment by afiore** [comment]
Notice that this PR doesn't build as we haven't yet published version 0.0.88-SNAPSHOT of membership commons. In order to run locally, please checkout membership common's master branch and use the `publishLocal` sbt task, which will publish the artefact on your dev machine.

**Comment by mario-galic** [comment]
`membership-common` master branch does not seem to have changes merged into yet, so I used [membership-zuora-consolidation](https://github.com/chrisjowen/membership-common/tree/membership-zuora-consolidation) branch. Creation of digital subscription works as a registered user as well as a guest user according to Zuora and SF.

**Comment by chrisjowen** [comment]
@tudorraul can you please review this today?

**Comment by chrisjowen** [comment]
@mario-galic thats my personal fork your looking at the membership-commons PR is https://github.com/guardian/membership-common/pull/91

**Pull request closed without merging**
