### PR TITLE
Fix 500 page layout

### PR DESCRIPTION
**Pull request by afiore**
This should fix a problem reported by @rtyley after #40 got merged.
screen shot 2015-06-19 at 16 54 03

@davidrapson, is there a better way of doing this? I don't really know how this grid system works...

### CODE REVIEW

**Comment by davidrapson** [comment]
@afiore I don't actually use the `gs-` classes on Membership so I'm not that familiar with them. Layout here looks a little odd here anyway? Is there need for any grid classes on a page like this?

**Comment by afiore** [comment]
@davidrapson good point! I have removed the classes and is looking okish (i.e. paragraphs align one below the other..). As for the styling, I am afraid this is as far as my CSS skills go :no_mouth:

**Comment by afiore** [comment]
@rtyley happy for me to merge this in?

**Comment by rtyley** [comment]
:+1:

**Comment by afiore** [comment]
No noticeable regressions on prod ;)

**Pull request merged**
