### PR TITLE
display subscription name on the checkout confirmation page

### PR DESCRIPTION
**Pull request by tudorraul**
### Before 
screen shot 2015-07-16 at 11 50 00

### After
screen shot 2015-07-16 at 11 47 54

### CODE REVIEW

**Comment by tudorraul** [comment]
@afiore

**Comment by davidrapson** [comment]
:+1: LGTM me but build is failing

**Comment by afiore** [comment]
:+1: Looks substantially better ;)

**Comment by tudorraul** [comment]
the build was referring to a future version of `membership-common` which is now available.

**Pull request merged**
